/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Lista2026RouteImport } from './routes/lista2026'
import { Route as IndexRouteImport } from './routes/index'

const Lista2026Route = Lista2026RouteImport.update({
  id: '/lista2026',
  path: '/lista2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lista2026': typeof Lista2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lista2026': typeof Lista2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lista2026': typeof Lista2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lista2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lista2026'
  id: '__root__' | '/' | '/lista2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Lista2026Route: typeof Lista2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lista2026': {
      id: '/lista2026'
      path: '/lista2026'
      fullPath: '/lista2026'
      preLoaderRoute: typeof Lista2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Lista2026Route: Lista2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
